services:
  runner:
    image: # Your image in a container registry like ECR, dockerhub, etc.
    entrypoint: ./start.sh
    environment:
      - OWNER= # Owner of the repository
      - ACCESS_TOKEN= # Github token with access to the repository
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

