services:
  runner:
    image: alexmllo/actions-image:latest
      # restart: always
    environment:
      - OWNER=alexmllo
      - REPO=test-pipelines
      - ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          cpus: '0.25'
          memory: 120M
        reservations:
          cpus: '0.15'
          memory: 60M
